version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=docjw
      - POSTGRES_USER=docjw
      - POSTGRES_PASSWORD=Car58it91res235
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  
  preview:
    image: nestjs-preview:1.0.0
    container_name: netsjs-preview
    build:
      context: .
      dockerfile: nest.Dockerfile
      args:
        DOTENV_FILE: preview.env
    command: npm run start:prod
    depends_on:
      - postgres
    ports:
      - 3000:3000
    restart: always
  
volumes:
  postgres: