version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=docjw
      - POSTGRES_USER=docjw
      - POSTGRES_PASSWORD=Car58it91res235
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped
  
volumes:
  postgres: